---
- name: create the security group for the webserver 
  amazon.aws.ec2_security_group:
    name: webserver-secgrp
    description: allow http and https traffic
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports: 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow ssh access from bastion host
      - proto: tcp
        ports: 
        - 80
        group_name: "{{ alb_secgrp.group_name }}"
        rule_desc: allow health_check pings from the load balancer
  register: webserver_secgrp

- name: create the security group for the bastion host
  amazon.aws.ec2_security_group:
    name: bastion-secgrp
    description: allow ssh, http and https traffic
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
        - 22
        - 80
        - 443
        cidr_ip: 0.0.0.0/0
        rule_desc: allow the bastion host to serve as a NAT instance
  register: bastion_secgrp
  
- name: create the security group for the load balancer
  amazon.aws.ec2_security_group:
    name: alb-secgrp
    description: sg with rule descriptions
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
        - 80
        - 443
        cidr_ip: 0.0.0.0/0
        rule_desc: allow inbound traffic on port 80 & 443
    rules_egress:
      - proto: tcp
        ports:
        - 80
        - 443
        cidr_ip: 0.0.0.0/0
        rule_desc: allow outbound traffic on port 80 & 443
  register: alb_secgrp