instance_type: t2.micro
amazon_image: ami-0b5eea76982371e91
nat_image: ami-04027ecc3f40c1801
region: us-east-1
ubuntu_image: ami-0574da719dca65348
my_vpc: webapp-vpc
vpc_block: 10.0.0.0/16
my_subnet: challenge-subnet
subnet_block: challenge 10.0.0.0/24
# public az
public_az_1a: us-east-1a
public_az_1a_block: 10.0.0.0/20
public_az_1b: us-east-1b
public_az_1b_block: 10.0.16.0/20
# private az
private_az_1a: us-east-1a
private_az_1a_block: 10.0.128.0/20
private_az_1b: us-east-1b
private_az_1b_block: 10.0.144.0/20
# public subnet
public_subnet_1a: challenge-subnet-public1-us-east-1a
public_subnet_1b: challenge-subnet-public2-us-east-1b
# private subnet
private_subnet_1a: challenge-subnet-private1-us-east-1a
private_subnet_1b: challenge-subnet-private2-us-east-1b
# igw
igw: challenge-igw
# routes
public_rtb: challenge-rtb-public
private_rtb_1a: challenge-rtb-private1-us-east-1a
private_rtb_1b: challenge-rtb-private2-us-east-1b
# 
script: "{{ lookup('file', 'script.sh') }}"
ssl_cert: arn:aws:acm:us-east-1:816652808963:certificate/ad856481-cdb3-494a-8ca1-73d22349ba57