# tasks for /roles/aws/tasks/
---
- name: create a logical network
  import_tasks: aws-vpc/main.yml

- name: create all security groups
  import_tasks: aws-sec-grps/main.yml

- name: create instance key pair
  import_tasks: aws-key/main.yml

- name: create all instances
  import_tasks: aws-ec2/main.yml

- name: create a load balancer
  import_tasks: aws-alb/main.yml

- name: create a route to the internet via the bastion
  import_tasks: aws-vpc/private_route.yml